<?php
/**
 * Created by PhpStorm.
 * User: w01e6742rahl
 * Date: 13.08.17
 * Time: 10:44
 */

namespace src\AppBundle\Steffen;


class Courses
{
    // ToDo fetch data from csv file
    private $csv = array(
        array(
            'id' => 1,
            'abbr' => "ADS",
            'name' => "Algorithmen & Datenstrukturen",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "17,9",
            'examws' => 11,
            'examss' => 11,
            'semester' => 3,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 2,
            'abbr' => "BWL",
            'name' => "Betriebswirtschaftslehre",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 5,
            'examss' => 5,
            'semester' => 4,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 3,
            'abbr' => "CAB(S)",
            'name' => "Computerarchitektur & Betriebssysteme",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 5,
            'examss' => 5,
            'semester' => 1,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 4,
            'abbr' => "CG",
            'name' => "Computergrafik",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "17,9",
            'examws' => 11,
            'examss' => 13,
            'semester' => 3,
            'lecture' => 2,
            'lecture_mandatory' => 1),
        array(
            'id' => 5,
            'abbr' => "DB",
            'name' => "Datenbanken",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "17,23,6",
            'examws' => 10,
            'examss' => 10,
            'semester' => 3,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 6,
            'abbr' => "EI",
            'name' => "Einführung in die Informatik",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 8,
            'examss' => 8,
            'semester' => 1,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 7,
            'abbr' => "EWP",
            'name' => "Einführung in die wiss. Projektarbeit",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 15,
            'examws' => "8,9,10",
            'examss' => "5,9",
            'semester' => 4,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 8,
            'abbr' => "GIS",
            'name' => "Grundlagen der IT-Sicherheit",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => "17,23,25",
            'examws' => 8,
            'examss' => 8,
            'semester' => 4,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 9,
            'abbr' => "GP1",
            'name' => "Grundlagen der Programmierung 1",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 5,
            'examss' => 5,
            'semester' => 1,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 10,
            'abbr' => "GP2",
            'name' => "Grundlagen der Programmierung 2",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 9,
            'examws' => 4,
            'examss' => 4,
            'semester' => 2,
            'lecture' => 3,
            'lecture_mandatory' => 0),
        array(
            'id' => 11,
            'abbr' => "IMG",
            'name' => "Internetanwendungen für mobile Geräte",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => "10,18,20,26",
            'examws' => 0,
            'examss' => "6,8",
            'semester' => 4,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 12,
            'abbr' => "INM",
            'name' => "Informationsmanagement",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 2,
            'examws' => 8,
            'examss' => "8,9",
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 13,
            'abbr' => "ISP",
            'name' => "Internet-Serverprogrammierung",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => "9,10",
            'examws' => 8,
            'examss' => 8,
            'semester' => 4,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 14,
            'abbr' => "ITR",
            'name' => "IT-Recht",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 12,
            'examss' => 12,
            'semester' => 3,
            'lecture' => 2,
            'lecture_mandatory' => 1),
        array(
            'id' => 15,
            'abbr' => "KFS",
            'name' => "Kommunikation, Führung und Selbstmanagement",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => "3,4,5",
            'examss' => "4,5,6",
            'semester' => 1,
            'lecture' => 3,
            'lecture_mandatory' => 3),
        array(
            'id' => 16,
            'abbr' => "KN1",
            'name' => "Kommunikationsnetze 1",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 4,
            'examss' => 4,
            'semester' => 2,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 17,
            'abbr' => "LA",
            'name' => "Lineare Algebra",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 8,
            'examss' => 8,
            'semester' => 1,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 18,
            'abbr' => "MCK",
            'name' => "Mensch-Computer-Kommunikation",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 3,
            'examss' => 3,
            'semester' => 2,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 19,
            'abbr' => "MD1",
            'name' => "Mediendesign 1",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => "3,4,5",
            'examss' => "4,8,9",
            'semester' => 1,
            'lecture' => 2,
            'lecture_mandatory' => 1),
        array(
            'id' => 20,
            'abbr' => "MD2",
            'name' => "Mediendesign 2",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 19,
            'examws' => 2,
            'examss' => "1,2,3,4",
            'semester' => 2,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 21,
            'abbr' => "MMT",
            'name' => "Multimediatechnik",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "17,23,9",
            'examws' => 10,
            'examss' => 10,
            'semester' => 3,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 22,
            'abbr' => "PFW",
            'name' => "Pattern & Frameworks",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "10,13,24,3,18,5",
            'examws' => "10,11,12",
            'examss' => 9,
            'semester' => 5,
            'lecture' => 2,
            'lecture_mandatory' => 1),
        array(
            'id' => 23,
            'abbr' => "RF",
            'name' => "Relationen & Funktionen",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 1,
            'examss' => 1,
            'semester' => 2,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 24,
            'abbr' => "SWT",
            'name' => "Softwaretechnik",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 5,
            'examss' => 5,
            'semester' => 4,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 25,
            'abbr' => "TI",
            'name' => "Theoretische Informatik",
            'compulsory' => 1,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 6,
            'examws' => 1,
            'examss' => 1,
            'semester' => 2,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 26,
            'abbr' => "WEB",
            'name' => "Web-Programmierung",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "17,23,6",
            'examws' => "10,11,12",
            'examss' => "10,12",
            'semester' => 3,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 27,
            'abbr' => "AAM",
            'name' => "Anforderungsanalyse und Modellierung",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 0,
            'semester' => 5,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 28,
            'abbr' => "AKB",
            'name' => "Ausgewählte Kapitel zu Betriebssystemen",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => "3,6,9",
            'examws' => 5,
            'examss' => 5,
            'semester' => 5,
            'lecture' => 3,
            'lecture_mandatory' => 1),
        array(
            'id' => 29,
            'abbr' => "BBV",
            'name' => "Bildbearbeitung und -verarbeitung",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 0,
            'semester' => 5,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 30,
            'abbr' => "CMS",
            'name' => "Content-Management-Systeme",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => "9,10",
            'examss' => 12,
            'semester' => 5,
            'lecture' => 3,
            'lecture_mandatory' => 0),
        array(
            'id' => 31,
            'abbr' => "CPP",
            'name' => "Programmierung in C++",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 0,
            'semester' => 5,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 32,
            'abbr' => "EPM",
            'name' => "Einführung Projektmanagement",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 9,
            'examss' => "2,9",
            'semester' => 6,
            'lecture' => 2,
            'lecture_mandatory' => 2),
        array(
            'id' => 33,
            'abbr' => "GVW",
            'name' => "Grundlagen virtueller Welten",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 0,
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 34,
            'abbr' => "KN2",
            'name' => "Kommunikationsnetze 2",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 16,
            'examws' => 2,
            'examss' => 8,
            'semester' => 6,
            'lecture' => 3,
            'lecture_mandatory' => 2),
        array(
            'id' => 35,
            'abbr' => "MWK",
            'name' => "Medienwirtschaft & Kommunikationspolitik",
            'compulsory' => 0,
            'ws' => '1',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 9,
            'examss' => 9,
            'semester' => 6,
            'lecture' => 1,
            'lecture_mandatory' => 1),
        array(
            'id' => 36,
            'abbr' => "OOS",
            'name' => "Objektorientierte Skriptsprachen",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '1',
            'conditions' => "3,9",
            'examws' => 9,
            'examss' => 9,
            'semester' => 5,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 37,
            'abbr' => "RMA",
            'name' => "Rich-Media-Anwendungen",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '1',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 11,
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 38,
            'abbr' => "SMDA",
            'name' => "Sicherheit von Mediendaten & -anwendungen",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 0,
            'examss' => 0,
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 39,
            'abbr' => "TEE",
            'name' => "Technisches Englisch",
            'compulsory' => 0,
            'ws' => '0',
            'ss' => '0',
            'conditions' => 0,
            'examws' => 4,
            'examss' => 0,
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 40,
            'abbr' => "PRO",
            'name' => "Projekt",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => "17,23,10,7,24",
            'examws' => 0,
            'examss' => 0,
            'semester' => 5,
            'lecture' => 0,
            'lecture_mandatory' => 0),
        array(
            'id' => 41,
            'abbr' => "BA",
            'name' => "Bachlor",
            'compulsory' => 1,
            'ws' => '1',
            'ss' => '1',
            'conditions' => 40,
            'examws' => 0,
            'examss' => 0,
            'semester' => 6,
            'lecture' => 0,
            'lecture_mandatory' => 0)
    );

    public function fetch(Array $selected_courses, $semester)
    {
        $this->sort();
        $courses = array();
        $cond_delimiter = ',';
        $get_conditions = array('0');

        if (!empty($selected_courses))
        {
            $get_conditions = array_merge($get_conditions, $selected_courses);
        }



        // ToDo group by semester
        for ($i = 0; $i < count($this->csv); $i++)
        {
            $ws = '-';
            $ss = '-';
            $assignable = 0;
            if (0 == count(array_diff(explode($cond_delimiter, $this->csv[$i]['conditions']), $get_conditions)))
            {
                $selected = (in_array($this->csv[$i]['id'], $get_conditions)) ? '1' : '0';
                if ($this->csv[$i]['ws'] === '1')
                {
                    $ws = 'WS';
                }
                if ($this->csv[$i]['ss'] === '1')
                {
                    $ss = 'SS';
                }
                if ($this->csv[$i][$semester] === '1')
                {
                    $assignable = 1;
                }
                $courses[] = array(
                    'id' => $this->csv[$i]['id'],
                    'name' => $this->csv[$i]['name'],
                    'selected' => $selected,
                    'wpf' => $this->csv[$i]['compulsory'],
                    'semester' => $ss . '/' . $ws,
                    'assignable' => $assignable
                );
            }
        }

        return $courses;
    }

    private function sort()
    {
        usort($this->csv,function ($a, $b)
        {
            if ($a["semester"] == $b["semester"]) {
                return 0;
            }
            return ($a["semester"] < $b["semester"]) ? -1 : 1;
        }
        );
    }
}
