parameters:
  courses:
    - id: 1
      abbr: "ADS"
      name: "Algorithmen & Datenstrukturen"
      compulsory: true
      ws: true
      ss: false
      conditions: [17, 9]
      examws: 11
      examss: 11
      semester: 3
      lecture: 3
      lecture_mandatory: 1

    - id: 2
      abbr: "BWL"
      name: "Betriebswirtschaftslehre"
      compulsory: true
      ws: false
      ss: true
      conditions: [0]
      examws: 5
      examss: 5
      semester: 4
      lecture: 3
      lecture_mandatory: 2

    - id: 3
      abbr: "CAB(S)"
      name: "Computerarchitektur & Betriebssysteme"
      compulsory: true
      ws: true
      ss: false
      conditions: [0]
      examws: 5
      examss: 5
      semester: 1
      lecture: 3
      lecture_mandatory: 1

    - id: 4
      abbr: "CG"
      name: "Computergrafik"
      compulsory: true
      ws: true
      ss: false
      conditions: [17, 9]
      examws: 11
      examss: 13
      semester: 3
      lecture: 2
      lecture_mandatory: 1

    - id: 5
      abbr: "DB"
      name: "Datenbanken"
      compulsory: true
      ws: true
      ss: false
      conditions: [17, 23, 6]
      examws: 10
      examss: 10
      semester: 3
      lecture: 3
      lecture_mandatory: 2

    - id: 6
      abbr: "EI"
      name: "Einführung in die Informatik"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: 8
      examss: 8
      semester: 1
      lecture: 3
      lecture_mandatory: 2

    - id: 7
      abbr: "EWP"
      name: "Einführung in die wiss. Projektarbeit"
      compulsory: true
      ws: true
      ss: true
      conditions: [15]
      examws: "8,9,10"
      examss: "5,9"
      semester: 4
      lecture: 3
      lecture_mandatory: 1

    - id: 8
      abbr: "GIS"
      name: "Grundlagen der IT-Sicherheit"
      compulsory: true
      ws: false
      ss: true
      conditions: [17, 23, 25]
      examws: 8
      examss: 8
      semester: 4
      lecture: 0
      lecture_mandatory: 0

    - id: 9
      abbr: "GP1"
      name: "Grundlagen der Programmierung 1"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: 5
      examss: 5
      semester: 1
      lecture: 3
      lecture_mandatory: 2

    - id: 10
      abbr: "GP2"
      name: "Grundlagen der Programmierung 2"
      compulsory: true
      ws: true
      ss: true
      conditions: [9]
      examws: 4
      examss: 4
      semester: 2
      lecture: 3
      lecture_mandatory: 0

    - id: 11
      abbr: "IMG"
      name: "Internetanwendungen für mobile Geräte"
      compulsory: true
      ws: false
      ss: true
      conditions: [10, 18, 20, 26]
      examws: 0
      examss: "6,8"
      semester: 4
      lecture: 0
      lecture_mandatory: 0

    - id: 12
      abbr: "INM"
      name: "Informationsmanagement"
      compulsory: true
      ws: false
      ss: true
      conditions: [2]
      examws: 8
      examss: "8,9"
      semester: 6
      lecture: 0
      lecture_mandatory: 0

    - id: 13
      abbr: "ISP"
      name: "Internet-Serverprogrammierung"
      compulsory: true
      ws: true
      ss: true
      conditions: [9, 10]
      examws: 8
      examss: 8
      semester: 4
      lecture: 3
      lecture_mandatory: 2

    - id: 14
      abbr: "ITR"
      name: "IT-Recht"
      compulsory: true
      ws: true
      ss: false
      conditions: [0]
      examws: 12
      examss: 12
      semester: 3
      lecture: 2
      lecture_mandatory: 1

    - id: 15
      abbr: "KFS"
      name: "Kommunikation, Führung und Selbstmanagement"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: "3,4,5"
      examss: "4,5,6"
      semester: 1
      lecture: 3
      lecture_mandatory: 3

    - id: 16
      abbr: "KN1"
      name: "Kommunikationsnetze 1"
      compulsory: true
      ws: false
      ss: true
      conditions: [0]
      examws: 4
      examss: 4
      semester: 2
      lecture: 0
      lecture_mandatory: 0

    - id: 17
      abbr: "LA"
      name: "Lineare Algebra"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: 8
      examss: 8
      semester: 1
      lecture: 3
      lecture_mandatory: 1

    - id: 18
      abbr: "MCK"
      name: "Mensch-Computer-Kommunikation"
      compulsory: true
      ws: false
      ss: true
      conditions: [0]
      examws: 3
      examss: 3
      semester: 2
      lecture: 0
      lecture_mandatory: 0

    - id: 19
      abbr: "MD1"
      name: "Mediendesign 1"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: "3,4,5"
      examss: "4,8,9"
      semester: 1
      lecture: 2
      lecture_mandatory: 1

    - id: 20
      abbr: "MD2"
      name: "Mediendesign 2"
      compulsory: true
      ws: false
      ss: true
      conditions: [19]
      examws: 2
      examss: "1,2,3,4"
      semester: 2
      lecture: 0
      lecture_mandatory: 0

    - id: 21
      abbr: "MMT"
      name: "Multimediatechnik"
      compulsory: true
      ws: true
      ss: false
      conditions: [17, 23, 9]
      examws: 10
      examss: 10
      semester: 3
      lecture: 3
      lecture_mandatory: 2

    - id: 22
      abbr: "PFW"
      name: "Pattern & Frameworks"
      compulsory: true
      ws: true
      ss: false
      conditions: [10, 13, 24, 3, 18, 5]
      examws: "10,11,12"
      examss: 9
      semester: 5
      lecture: 2
      lecture_mandatory: 1

    - id: 23
      abbr: "RF"
      name: "Relationen & Funktionen"
      compulsory: true
      ws: true
      ss: true
      conditions: [0]
      examws: 1
      examss: 1
      semester: 2
      lecture: 3
      lecture_mandatory: 2

    - id: 24
      abbr: "SWT"
      name: "Softwaretechnik"
      compulsory: true
      ws: false
      ss: true
      conditions: [0]
      examws: 5
      examss: 5
      semester: 4
      lecture: 0
      lecture_mandatory: 0

    - id: 25
      abbr: "TI"
      name: "Theoretische Informatik"
      compulsory: true
      ws: false
      ss: true
      conditions: [6]
      examws: 1
      examss: 1
      semester: 2
      lecture: 0
      lecture_mandatory: 0

    - id: 26
      abbr: "WEB"
      name: "Web-Programmierung"
      compulsory: true
      ws: true
      ss: false
      conditions: [17, 23, 6]
      examws: "10,11,12"
      examss: "10,12"
      semester: 3
      lecture: 3
      lecture_mandatory: 1

    - id: 27
      abbr: "AAM"
      name: "Anforderungsanalyse und Modellierung"
      compulsory: false
      ws: false
      ss: true
      conditions: [0]
      examws: 0
      examss: 0
      semester: 5
      lecture: 0
      lecture_mandatory: 0

    - id: 28
      abbr: "AKB"
      name: "Ausgewählte Kapitel zu Betriebssystemen"
      compulsory: false
      ws: true
      ss: false
      conditions: [3, 6, 9]
      examws: 5
      examss: 5
      semester: 5
      lecture: 3
      lecture_mandatory: 1

    - id: 29
      abbr: "BBV"
      name: "Bildbearbeitung und -verarbeitung"
      compulsory: false
      ws: false
      ss: true
      conditions: [0]
      examws: 0
      examss: 0
      semester: 5
      lecture: 0
      lecture_mandatory: 0

    - id: 30
      abbr: "CMS"
      name: "Content-Management-Systeme"
      compulsory: false
      ws: true
      ss: false
      conditions: [0]
      examws: "9,10"
      examss: 12
      semester: 5
      lecture: 3
      lecture_mandatory: 0

    - id: 31
      abbr: "CPP"
      name: "Programmierung in C++"
      compulsory: false
      ws: true
      ss: true
      conditions: [0]
      examws: 0
      examss: 0
      semester: 5
      lecture: 0
      lecture_mandatory: 0

    - id: 32
      abbr: "EPM"
      name: "Einführung Projektmanagement"
      compulsory: false
      ws: true
      ss: false
      conditions: [0]
      examws: 9
      examss: "2,9"
      semester: 6
      lecture: 2
      lecture_mandatory: 2

    - id: 33
      abbr: "GVW"
      name: "Grundlagen virtueller Welten"
      compulsory: false
      ws: true
      ss: false
      conditions: [0]
      examws: 0
      examss: 0
      semester: 6
      lecture: 0
      lecture_mandatory: 0

    - id: 34
      abbr: "KN2"
      name: "Kommunikationsnetze 2"
      compulsory: false
      ws: true
      ss: false
      conditions: [16]
      examws: 2
      examss: 8
      semester: 6
      lecture: 3
      lecture_mandatory: 2

    - id: 35
      abbr: "MWK"
      name: "Medienwirtschaft & Kommunikationspolitik"
      compulsory: false
      ws: true
      ss: false
      conditions: [0]
      examws: 9
      examss: 9
      semester: 6
      lecture: 1
      lecture_mandatory: 1

    - id: 36
      abbr: "OOS"
      name: "Objektorientierte Skriptsprachen"
      compulsory: false
      ws: false
      ss: true
      conditions: [3, 9]
      examws: 9
      examss: 9
      semester: 5
      lecture: 0
      lecture_mandatory: 0

    - id: 37
      abbr: "RMA"
      name: "Rich-Media-Anwendungen"
      compulsory: false
      ws: false
      ss: true
      conditions: [0]
      examws: 0
      examss: 11
      semester: 6
      lecture: 0
      lecture_mandatory: 0

    - id: 38
      abbr: "SMDA"
      name: "Sicherheit von Mediendaten & -anwendungen"
      compulsory: false
      ws: false
      ss: false
      conditions: [0]
      examws: 0
      examss: 0
      semester: 6
      lecture: 0
      lecture_mandatory: 0

    - id: 39
      abbr: "TEE"
      name: "Technisches Englisch"
      compulsory: false
      ws: false
      ss: false
      conditions: [0]
      examws: 4
      examss: 0
      semester: 6
      lecture: 0
      lecture_mandatory: 0

    - id: 40
      abbr: "PRO"
      name: "Projekt"
      compulsory: true
      ws: true
      ss: true
      conditions: [17, 23, 10, 7, 24]
      examws: 0
      examss: 0
      semester: 5
      lecture: 0
      lecture_mandatory: 0

    - id: 41
      abbr: "BA"
      name: "Bachlor"
      compulsory: true
      ws: true
      ss: true
      conditions: [40]
      examws: 0
      examss: 0
      semester: 6
      lecture: 0
      lecture_mandatory: 0
